# Generated by Django 3.1 on 2020-08-08 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemscompra',
            options={'verbose_name': 'ItemCompra', 'verbose_name_plural': 'Items Compra'},
        ),
    ]
