# Generated by Django 3.1 on 2020-08-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200807_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='costoProducto',
            field=models.FloatField(default=0.0, verbose_name='Precio de compra, modena colombiana'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=70, null=True, verbose_name='Breve descripcion'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_vnt',
            field=models.FloatField(default=0.0, verbose_name='Precio venta, modena colombiana'),
        ),
    ]
