# Generated by Django 3.1 on 2020-08-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200809_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscompra',
            name='precio',
            field=models.FloatField(default=0.0, verbose_name='Precio venta'),
        ),
    ]
