# Generated by Django 3.1 on 2020-08-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_itemscompra_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dirc',
            field=models.CharField(default='Calle/Av', max_length=50, verbose_name='Direccion entrega'),
        ),
    ]
