# Generated by Django 3.1 on 2020-08-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200809_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='cliente_Id',
            new_name='cliente_id',
        ),
    ]
