# Generated by Django 3.1 on 2020-08-10 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200809_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscompra',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad comprada'),
        ),
    ]
